default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("PG_USERNAME", "postgres") %>
  password: <%= ENV.fetch("PG_PASSWORD", "postgres") %>
  host: <%= ENV.fetch("PG_HOST", "localhost") %>

development:
  <<: *default
  database: test_dev_1